### ISSUE TITLE
Building with "dotnet build"

### ISSUE THREAD

**Issue by vaskoa** [MarcStan/resource-embedder#28]
Any plans to release a new nuget package that includes [commit b47ff93](https://github.com/MarcStan/resource-embedder/commit/b47ff931eff98ee68d49ef25e31bc69f288ee538)?

This is preventing me from building with `dotnet`.

Workaround: Build twice. 😁

**Comment by MarcStan** [comment]
Sorry must have forgotten to release back then.

I just published v2.2.0!

**Comment by MarcStan** [comment]
Appreciate it, but that's not necessary. :)
