### ISSUE TITLE
This Project is far from being Obsolete

### ISSUE THREAD

**Issue by softworkz** [MarcStan/resource-embedder#29]
> Single-file executables technically make the Resource Embedder project obsolete, although there are some use cases (e.g. [manually inject resources](https://github.com/MarcStan/resource-embedder/blob/master/docs/Core%20package%20usage.md)) that aren't (yet) covered natively by .Net Core.

We have a plugin ecosystem which we are migrating from proprietary to RESX localization patterns. The plugin management relies on having a single .dll per plugin in all its operations like packaging, downloading, installing, uninstalling and loading into the process using a custom non-file-based mechanism. Changing that would have been a nightmare and imposing a high risk of issues and regressions.

These days, It rarely happens that you adopt some library or project and it instantly solves the problem you are facing without additional effort. But in this case, it actually did.

Your project saved me quite an amount of time for working out a custom solution. It is still highly useful, and IMO, single-file publishing is an alternative for a limited range of cases only.

Thank you very much for sharing this!

softworkz
(feel free to close this non-issue right away)

**Comment by MarcStan** [comment]
Thanks for the kind words!

When they first announced it there were plenty of scenarios they had planned but looks like they never got implemented and I agree that as-is single file publishing doesn't cover all usecases that resource embedder supports.

Luckily this project doesn't require much/any maintenance so I'm glad it is still of value!
